const NRF_ERROR_BASE_NUM = 0x0;
const NRF_ERROR_SDM_BASE_NUM = 0x1000;
const NRF_ERROR_SOC_BASE_NUM = 0x2000;
const NRF_ERROR_STK_BASE_NUM = 0x3000;

const NRF_SUCCESS = NRF_ERROR_BASE_NUM + 0;
const NRF_ERROR_SVC_HANDLER_MISSING = NRF_ERROR_BASE_NUM + 1;
const NRF_ERROR_SOFTDEVICE_NOT_ENABLED = NRF_ERROR_BASE_NUM + 2;
const NRF_ERROR_INTERNAL = NRF_ERROR_BASE_NUM + 3;
const NRF_ERROR_NO_MEM = NRF_ERROR_BASE_NUM + 4;
const NRF_ERROR_NOT_FOUND = NRF_ERROR_BASE_NUM + 5;
const NRF_ERROR_NOT_SUPPORTED = NRF_ERROR_BASE_NUM + 6;
const NRF_ERROR_INVALID_PARAM = NRF_ERROR_BASE_NUM + 7;
const NRF_ERROR_INVALID_STATE = NRF_ERROR_BASE_NUM + 8;
const NRF_ERROR_INVALID_LENGTH = NRF_ERROR_BASE_NUM + 9;
const NRF_ERROR_INVALID_FLAGS = NRF_ERROR_BASE_NUM + 10;
const NRF_ERROR_INVALID_DATA = NRF_ERROR_BASE_NUM + 11;
const NRF_ERROR_DATA_SIZE = NRF_ERROR_BASE_NUM + 12;
const NRF_ERROR_TIMEOUT = NRF_ERROR_BASE_NUM + 13;
const NRF_ERROR_NULL = NRF_ERROR_BASE_NUM + 14;
const NRF_ERROR_FORBIDDEN = NRF_ERROR_BASE_NUM + 15;
const NRF_ERROR_INVALID_ADDR = NRF_ERROR_BASE_NUM + 16;
const NRF_ERROR_BUSY = NRF_ERROR_BASE_NUM + 17;
const NRF_ERROR_CONN_COUNT = NRF_ERROR_BASE_NUM + 18;
const NRF_ERROR_RESOURCES = NRF_ERROR_BASE_NUM + 19;

const BLE_GAP_EVT_BASE = 0x10;
const BLE_GATTC_EVT_BASE = 0x30;

const BLE_GAP_EVT_CONNECTED = BLE_GAP_EVT_BASE;
const BLE_GAP_EVT_DISCONNECTED = BLE_GAP_EVT_BASE + 1;
const BLE_GAP_EVT_CONN_PARAM_UPDATE = BLE_GAP_EVT_BASE + 2;
const BLE_GAP_EVT_SEC_PARAMS_REQUEST = BLE_GAP_EVT_BASE + 3;
const BLE_GAP_EVT_SEC_INFO_REQUEST = BLE_GAP_EVT_BASE + 4;
const BLE_GAP_EVT_PASSKEY_DISPLAY = BLE_GAP_EVT_BASE + 5;
const BLE_GAP_EVT_KEY_PRESSED = BLE_GAP_EVT_BASE + 6;
const BLE_GAP_EVT_AUTH_KEY_REQUEST = BLE_GAP_EVT_BASE + 7;
const BLE_GAP_EVT_LESC_DHKEY_REQUEST = BLE_GAP_EVT_BASE + 8;
const BLE_GAP_EVT_AUTH_STATUS = BLE_GAP_EVT_BASE + 9;
const BLE_GAP_EVT_CONN_SEC_UPDATE = BLE_GAP_EVT_BASE + 10;
const BLE_GAP_EVT_TIMEOUT = BLE_GAP_EVT_BASE + 11;
const BLE_GAP_EVT_RSSI_CHANGED = BLE_GAP_EVT_BASE + 12;
const BLE_GAP_EVT_ADV_REPORT = BLE_GAP_EVT_BASE + 13;
const BLE_GAP_EVT_SEC_REQUEST = BLE_GAP_EVT_BASE + 14;
const BLE_GAP_EVT_CONN_PARAM_UPDATE_REQUEST = BLE_GAP_EVT_BASE + 15;
const BLE_GAP_EVT_SCAN_REQ_REPORT = BLE_GAP_EVT_BASE + 16;

const BLE_GATTC_EVT_PRIM_SRVC_DISC_RSP = BLE_GATTC_EVT_BASE;
const BLE_GATTC_EVT_REL_DISC_RSP = BLE_GATTC_EVT_BASE + 1;
const BLE_GATTC_EVT_CHAR_DISC_RSP = BLE_GATTC_EVT_BASE + 2;
const BLE_GATTC_EVT_DESC_DISC_RSP = BLE_GATTC_EVT_BASE + 3;
const BLE_GATTC_EVT_ATTR_INFO_DISC_RSP = BLE_GATTC_EVT_BASE + 4;
const BLE_GATTC_EVT_CHAR_VAL_BY_UUID_READ_RSP = BLE_GATTC_EVT_BASE + 5;
const BLE_GATTC_EVT_READ_RSP = BLE_GATTC_EVT_BASE + 6;
const BLE_GATTC_EVT_CHAR_VALS_READ_RSP = BLE_GATTC_EVT_BASE + 7;
const BLE_GATTC_EVT_WRITE_RSP = BLE_GATTC_EVT_BASE + 8;
const BLE_GATTC_EVT_HVX = BLE_GATTC_EVT_BASE + 9;
const BLE_GATTC_EVT_TIMEOUT = BLE_GATTC_EVT_BASE + 10;

const sd_rpc_app_status_t = Object.freeze({
    PKT_SEND_MAX_RETRIES_REACHED: 0,
    PKT_UNEXPECTED: 1,
    PKT_ENCODE_ERROR: 2,
    PKT_DECODE_ERROR: 3,
    PKT_SEND_ERROR: 4,
    IO_RESOURCES_UNAVAILABLE: 5,
    RESET_PERFORMED: 6,
    CONNECTION_ACTIVE: 7,
});

const sd_rpc_log_severity_t = Object.freeze({
    SD_RPC_LOG_TRACE: 0,
    SD_RPC_LOG_DEBUG: 1,
    SD_RPC_LOG_INFO: 2,
    SD_RPC_LOG_WARNING: 3,
    SD_RPC_LOG_ERROR: 4,
    SD_RPC_LOG_FATAL: 5,
});
